# Generated by Django 5.1a1 on 2025-03-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Введите название вида курса (например, 'Повышение квалификации').", max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически создается из названия.', unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о виде курса (необязательно).', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид курса',
                'verbose_name_plural': 'Виды курсов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text="Введите название курса (например, 'Основы программирования').", max_length=100, verbose_name='Название курса')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически создается из названия.', unique=True, verbose_name='URL')),
                ('anons', models.TextField(help_text='Короткое описание курса, которое будет отображаться в списке.', verbose_name='Краткое описание')),
                ('text', models.TextField(help_text='Полное описание курса с программой обучения.', verbose_name='Полное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении записи.', verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Определяет, отображается ли курс на сайте.', verbose_name='Активен')),
                ('course_type', models.ForeignKey(help_text='Выберите категорию курса.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='main.coursetype', verbose_name='Вид курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
                'unique_together': {('title', 'course_type')},
            },
        ),
    ]
